#!/bin/bash
ls $1/ligand/ |sed '{s/.pdbqt//}' | parallel -j $2 --tag "vina --score_only --receptor $1/receptor.pdbqt --ligand $1/ligand/{}.pdbqt" |grep "Affinity" |awk '{print $1,$3}'  >$1/score_vina.record
